version: '3'

services:
  traefik:
    image: traefik
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/etc/traefik/acme/acme.json:/etc/traefik/acme/acme.json"
      - "./traefik.toml:/etc/traefik/traefik.toml"
      - "/var/run/docker.sock:/var/run/docker.sock"
    labels:
      - "traefik.port=8080"
      - "traefik.enable=true"
      - "traefik.backend=traefik"
      - "traefik.frontend.auth.basic.users=admin:$$2y$$05$$1/4YQ.nZ3eFWSMrOS4UOVOUMKVIbxHS8t4i7a5CgjqZ/3ytGnVlea"
      - "traefik.frontend.rule=Host:traefik.tandon.singles"
    networks:
      - traefik-proxy
      - internal


  flasq:
    build: .
    restart: always
    expose:
      - "80"
    volumes:
      - "$HOME/.data:/flasq/web/.data:rw"
    labels:
      - "traefik.enable=true"
      - "traefik.port=80"
      - "traefik.backend=flasq"
      - "traefik.frontend.rule=Host:tandon.singles"
    environment:
      - "PORT=80"
      - "WORKERS=4"
      - "SITENAME=tandon.singles"
    networks:
      - traefik-proxy
      - internal


  db:
    build: db
    expose:
      - "3306"
    environment:
      - "MYSQL_ROOT_PASSWORD=password"
    labels:
      - "traefik.enable=false"
    networks:
      - internal

networks:
  internal:
    internal: true
  traefik-proxy:
    external:
      name: traefik-proxy
