logLevel = "WARN" #DEBUG, INFO, WARN, ERROR, FATAL, PANIC
defaultEntryPoints = ["http", "https"]
InsecureSkipVerify = true 

[entryPoints]
  [entryPoints.http]
  address = ":80"
  compress = true
    [entrypoints.http.whitelist]
      sourceRange = ["128.238.0.0/16","216.165.0.0/16"]
      useXForwardedFor = true
    [entryPoints.http.redirect]
    entryPoint = "https"
  [entryPoints.https]
  address = ":443"
  compress = true
    [entrypoints.https.whitelist]
      sourceRange = ["128.238.0.0/16","216.165.0.0/16"]
      useXForwardedFor = true
    [entryPoints.https.tls]

[api]
  [api.auth.basic]
  users = ["admin:$2y$05$1/4YQ.nZ3eFWSMrOS4UOVOUMKVIbxHS8t4i7a5CgjqZ/3ytGnVlea"]
entryPoint = "https"
dashboard = true

[acme]
email = "johncunniff1248@gmail.com"
storage="/etc/traefik/acme/acme.json"
entryPoint = "https"
acmeLogging = true
onHostRule = true
  [acme.httpChallenge]
  entryPoint = "http"

[docker]
endpoint = "unix:///var/run/docker.sock"
domain = "tandon.singles"
watch = true
